---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zoran.georgevici.
--- DateTime: 8/9/2018 3:08 PM
---

function create_siegetruck_attachments ()
--    <vehicle id="siegeTruck1" paintjob="2" interior="0" alpha="255" model="443" plate="V102DEX" dimension="0" color="159,74,62,0,0,0,0,0,0,0,0,0" posX="0" posY="0" posZ="5" rotX="0" rotY="0" rotZ="0"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {3593,0.09961,0.40039,6.8,14.249,0,0,1, false,true},--
    {2978,-1.7,2.7,7.4,0,0,0,1, false,true},--
    {2978,1.9,2.7,7.4,0,0,0,1, false,true},--
    {5152,0.1,-4.4,5.3,0,49.25,268.25,1, false,true},--
    {2990,1.5,-1.1,6,0,0,90.25,0.6, true},
    {2990,-1.5,-1,6.2,0,0,270.242,0.6, true},
    {6865,0,5.8,5.3,0,0,224.247,0.2, false},
    {2978,0,4.7,5.7,359.25,0,0,1, false},
    {1190,-1.3,5.6,4.3,0,0,0.75,1.5, true},
    {1190,1.8,-5.8,4.3,0,0,179.995,2, true},
    {1217,1.90039,-5.7002,4.3,0,0,31.745,1, true,true},--
    {1953,1.5,-5.2,5.7,0,270,181.75,1, true,true},--
    {1222,-1.9,-5.7,4.5,0,0,0,1, true,true},--
    {1411,0,3.5,7.1,285.258,1.9,1.833,1, false},
    {1449,1.7,3.5,7.8,0,0,167.25,1, false,true},--
    {1449,-1.6,3.5,7.9,0.989,7.251,196.115,1, false,true},--
    {1411,0.7,-1.1,4.7,271.5,359.999,270.328,1, false},
    {1411,-0.7,-0.9,4.7,272.262,276.234,7.821,1, false},
    {2908,1.5,-1.09961,8.2,284.398,154.039,300.872,1, false,true},--
    {2908,-1.5,-4,8.4,284.421,103.747,110.296,1, false,true},--
    {2906,0.40039,5.90039,4.3,24.637,113.06,294.395,1, false,true},--
    {2906,-2.4,4.9,7.6,15.864,272.072,44.959,1, false,true},--
    {2908,-0.5,5.7,4.6,297.048,345.018,278.714,1, false},
    {1185,1.4,5.3,4.8,0,0,0.75,1.4, true},
    {1185,-1.5,-6.9,4.2,0,0,180.747,1.5, true},
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable

end

function create_lurker_attachments ()
-- <vehicle id="thevehicle" paintjob="3" interior="0" alpha="255" model="545" plate="KAMIKABO" dimension="0" posX="2492.6006" posY="-1679.2998" posZ="13.3" rotX="0" rotY="0" rotZ="0" upgrades="1025" color="49,49,49,93,80,73,0,0,0,0,0,0"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {2371,2492.5,-1680.3,13,0,0,0,1, false},
    {1185,2491.5,-1681.6,12.8,0,0,179,1, true},
    {2371,2492.3,-1680.6,13.2,0,89.75,0,1, false},
    {2371,2492.8,-1680.6,13.1,0,272.497,0,1, false},
    {1115,2492.6001,-1677.4,12.7,0,0,358.75,1.5, true},
    {2056,2491.8999,-1678.6,13.3,0,0,265.25,1, false}
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable

end

function create_kamikaboom_attachments ()
-- <vehicle id="thevehicle" paintjob="3" interior="0" alpha="255" model="545" plate="KAMIKABO" dimension="0" posX="2492.6006" posY="-1679.2998" posZ="13.3" rotX="0" rotY="0" rotZ="0" upgrades="1025" color="49,49,49,93,80,73,0,0,0,0,0,0"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {2371,2492.5,-1680.3,13,0,0,0,1, false},
    {1218,2492.5,-1680.5,14.4,49.5,90,0,1, true},
    {1225,2492.5,-1681.1,13.4,359.065,339.247,89.646,1, true},
    {1225,2492.3,-1679.7,14.4,90,0,91.999,1, true},
    {1185,2491.5,-1681.6,12.8,0,0,179,1, true},
    {2371,2492.3,-1680.6,13.2,0,89.75,0,1, false},
    {2371,2492.8,-1680.6,13.1,0,272.497,0,1, false},
    {1115,2492.6001,-1677.4,12.7,0,0,358.75,1.5, true},
    {2056,2491.8999,-1678.6,13.3,0,0,265.25,1, false},
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable

end

function create_meatwagon_attachments ()
--<vehicle id="meatwagontrailer" paintjob="3" interior="0" alpha="255" model="591" plate="MEAT!" dimension="0" color="113,30,24,245,245,245,0,0,0,0,0,0" posX="2474.2" posY="-1673.2" posZ="14" rotX="0" rotY="0" rotZ="0" upgrades="1025"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {1411,2473.3,-1671.3,15.4,318.502,359.332,89.558,1, false},
    {2060,2473.3999,-1676.8,14,0,0,0,1, false,true},--
    {2060,2474.7,-1676.9,14,0,0,0,1, false,true},--
    {2060,2474.6001,-1676.9,14.2,0,0,8,1, false,true},--
    {2060,2473.3999,-1676.8,14.2,0,0,340,1, false},--
    {1411,2474.8999,-1670.9,15.4,318.499,359.33,271.055,1, false},
    {1254,2475.5,-1673.8,15.4,1.063,31.756,87.842,3, false},
    {1254,2475.5,-1673,15,1.191,342.746,88.867,3, false},
    {1414,2472.8,-1672.2,15,0,0,270,1, false},
    {1474,2474.2,-1666.2,17.3,334.507,358.615,357.654,1, false,true},--
    {2978,2474.2,-1674.6,16.2,0,0,0,1, false,true},--
    {2978,2474.8999,-1676.1,13.8,0,0,270,1, false,true},--
    {2978,2473.6001,-1676.1,13.8,0,0,270,1, false,true},--
    {1472,2474.2,-1667.8,16.9,0,0,0.5,1, false,true},--
    {1472,2474.2,-1666.4,17.8,0,0,0.5,1, false,true},--
    {1448,2474.3,-1664.8,18.3,272.75,180,181.25,1, false,true},--
    {1448,2473.5,-1665.3,18.3,272.747,179.995,271.747,1, false,true},--
    {1448,2475,-1665.5,18.3,272.747,179.995,87.747,1, false,true},--
    {2978,2474.2,-1665.8,18.2,0,0,89.25,1, false,true},--
    {3092,2474.2,-1664.6,17.9,0.25,182.5,343.239,1, false,true},--
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable

end

function create_peacekeepervan_attachments ()
--    <vehicle id="vehicle (Utility Van) (2)" paintjob="3" interior="0" alpha="255" model="552" plate="TBGL VT5" dimension="0" posX="2486.5" posY="-1675.6" posZ="13.1" rotX="0" rotY="0" rotZ="0" color="47,61,90,158,164,171,0,0,0,0,0,0"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {2930,2485.5,-1675.3,13.5,271.25,0,0,1, false},
    {2930,2487.6001,-1675.3,13.5,271.247,0,0,1, false},
    {2930,2487.6001,-1675.4,13.9,273.019,65.627,333.347,0.8, false},
    {2930,2487.6001,-1678,13.1,271.241,0,270,0.8, false},
    {1238,2486,-1678.3,13.5,0,0,0,1, false,true},--
    {2978,2486.5,-1677.3,13.1,0,0,0,1, false},
    {2978,2486.5,-1676,13.1,0,0,0,1, false},
    {2680,2487.6001,-1678,14.4,0,0,61.503,1.7, false},
    {1411,2485.3999,-1676.6,14.8,0,0,90.75,0.5, false,true},--
    {1411,2487.6001,-1676.7,14.8,0,0,270.25,0.5, false,true},--
    {2957,2486.5,-1676.7,15.2,88.232,314.993,134.993,0.64, false},
    {2930,2487.6001,-1678,13.8,271.241,0,270,0.8, false},
    {1778,2486.2,-1677.5,13.2,0,0,260,1, false,true},--
    {3350,2485.5,-1678.4,13.5,0,0,0.235,0.5, false},
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable

end

function create_roadwarrior_attachments ()
--<vehicle id="vehicle" paintjob="3" interior="0" alpha="255" model="549" plate="KILLZOR" dimension="0" posX="2524.8999" posY="-1463.3" posZ="23.8" rotX="0" rotY="0" rotZ="270" upgrades="1017,1020,1025,1009,1144" color="32,32,32,93,80,73,32,32,32,0,0,0"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {1115,2527.3999,-1463.3,23.3,0,0,270,2, true},
    {1100,2524.6001,-1463.3,23.8,0,0,270,1, false},
    {1089,2524.8999,-1463.3,23.8,0,0,268.75,1, false},
    {1010,2522.7,-1464.4,23.9,88.939,134.998,223.998,1, false},
    {1010,2522.7,-1462.2,23.8,273.536,8.135,10.605,1, false},
    {1185,2522.3,-1462.3,23.9,0,0,90,1, true},
    {2978,2522.8999,-1463.3,24,0,354.5,0.5,0.8, false},
    {2962,2523.7,-1463.2,24.1,301.008,358.544,268.752,6, true},
    {2371,2525.8999,-1463.7,23.7,0,268.25,90,0.7, false},
    {2371,2524.8,-1462.9,23.7,0,271.498,269.5,0.7, false},
    {2371,2525.5,-1463.3,23.3,0,0,90,1.2, false},
    {2978,2524.8999,-1463.3,24.6,0,0,90.5,0.8, false},
    {3280,2526.6001,-1463.3,24.1,0,5.5,1.145,1, false},
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable

end

function create_tradeboat_attachments ()
  -- <vehicle id="tradeboatcdf" paintjob="3" interior="0" alpha="255" model="453" plate="KVQ7JEE" dimension="0" color="158,158,158,158,164,171,0,0,0,0,0,0" posX="2103.9004" posY="-97.2998" posZ="0" rotX="0" rotY="0" rotZ="119.998"></vehicle>
  local objtable = {}
  for i,v in ipairs({
    {3577,2106.4004,-95.90039,0.7,0,0,117.74,0.8, false},
    {2062,2098.7998,-100.2002,1.90025,0,1.747,0,1, true},
    {2969,2100.3999,-100.6,1.3,0,0,7.5,1.5, false},
    {2972,2106.6006,-95,1.2,0,0,297.746,0.7, false},
    {2978,2099.9004,-99.5,1.5,0,0,299.993,1, false},
    {3578,2106.1006,-98.20019,0.9,0,0,34.492,0.09, false},
    {3578,2104.2998,-94.90039,0.9,0,0,206.993,0.09, false},
    {2359,2106.1006,-96.20019,1.5,0,0,0,1, false},
    {2888,2101.1006,-98.09961,2.8,332.249,1.121,110.77,0.26814, true},
    {3872,2096.5,-101.90039,2.5,0,25.746,31.498,0.8, false},
    {2888,2101.7002,-98,3.7,0,0,109.99,0.2, true},
    {2888,2102.2,-99,3.7,0,0,122.245,0.2, true},
    {2888,2102.1006,-99.20019,3.3,0,0,155.495,0.2, true},
    {1670,2100.8,-99.3,1.7,0,0,0,1, true},
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable
end

function create_warrig_attachments ()
  --  <vehicle id="warrigtruck" paintjob="3" interior="0" alpha="255" model="515" plate="4-TH3-HORDE" dimension="0" color="179,67,49,63,63,63,0,0,0,0,0,0" posX="2481.2" posY="-1669.8" posZ="14.5" rotX="0" rotY="0" rotZ="0" upgrades=""></vehicle>

  local objtable = {}

  for i,v in ipairs({
    {1411,2482,-1670.6,13.4,272.75,0,270,1, false},
    {1411,2480.5,-1670.5,13.4,272.747,0,90,1, false},
    {1414,2479.8999,-1669.8,14.9,0,88.75,270,0.5, false},
    {1424,2479.7,-1672.9,14.3,0,0,91,1, false},
    {1424,2482.6001,-1673,14.3,0,0,91,1, false},
    {2978,2481.2,-1671.6,13.9,0,0,0,1, false,true},--
    {2978,2481.1001,-1670.3,16,0,0,0,1, false,true},--
    {2060,2480.5,-1668.6,15.8,0,0,0,1, false},
    {2060,2481.3,-1668.6,15.8,0,0,20,1, false},
    {2060,2481.8999,-1668.6,15.8,0,0,339.995,1, false},
    {2060,2481.8999,-1668.6,15.9,0,0,349.994,1, false,true},--
    {2060,2481.1001,-1668.6,16,0,0,349.991,1, false,true},--
    {2060,2480.5,-1668.6,16,0,0,9.991,1, false,true},--
    {2060,2480.5,-1668.6,16.2,0,0,349.987,1, false,true},--
    {2060,2481.8,-1668.7,16.1,0,0,9.986,1, false,true},--
    {3872,2481.2,-1660.5,14.3,0,26.25,270,0.6, false,true},--
    {2888,2481,-1665.5,15.2,0,275,0,0.3, true},
    {2888,2481.8,-1665.5,15.2,0,274.999,0,0.3, true},
    {2887,2481.6001,-1665.6,15,0,0,0,0.28, false},
    {2887,2480.8,-1665.6,15,0,0,0,0.28, false},
  }) do
    local obj = createObject(v[1], v[2], v[3], v[4], v[5], v[6], v[7])
    setObjectScale(obj, v[8])
    setElementDimension(obj, 0)
    setElementInterior(obj, 0)
    setElementDoubleSided(obj, v[9])
    if v[10] then setElementCollisionsEnabled(obj,true) else setElementCollisionsEnabled(obj,false) end
    table.insert(objtable,obj)
  end
  return objtable
end